language: python
python:
  - '3.6'
install:
  - pip install tensorflow
  - pip install keras
  - pip install gym
  - pip install opencv-python
  - pip install Pillow
script:
  - python src/dqn/model_test.py
  - python src/run_soccer_test.py